name: Echo on Pull Request

# Memicu workflow pada pull request ke branch 'main'
on:
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo Check Makanan
        run: echo "Oh ini benar bukan makanan"

      - name: Echo Check Dessert
        run: echo "Oh ini benar bukan dessert"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo Check Valid tidak ada barang berbahaya
        run: echo "Oh ini benar tidak ada yang bahaya"